### ISSUE TITLE
Change `df` to `dat` in the code and docs

### ISSUE THREAD

**Issue by jjvenky** [paukes/pCO2calc#1]
It's dangerous to use `df` as a `data.frame` since `df` is actually a pre-existing function!

This can lead to confusion and the "Object of type 'closure' is not subsettable" error. See here for Jenny Bryan's talk which includes reference to this https://rstudio.com/resources/rstudioconf-2020/object-of-type-closure-is-not-subsettable/

**Comment by paukes** [comment]
Great point! Fixed in recent update.
